import type { ComponentCatalogRecords } from "@/application/contracts";

const capabilities: ComponentCatalogRecords["capabilities"] = [
  {
    id: "capability-web-interface",
    label: "Web interface",
    description: "Presents interactive browser experiences to users.",
    category: "interface",
    iconKey: "browser",
    connectionRoles: ["request", "dependency"],
  },
  {
    id: "capability-api",
    label: "API",
    description: "Exposes synchronous application operations and data.",
    category: "interface",
    iconKey: "brackets",
    connectionRoles: ["request", "dependency", "data"],
  },
  {
    id: "capability-compute",
    label: "Compute",
    description: "Executes application workloads and background processing.",
    category: "compute",
    iconKey: "cpu",
    connectionRoles: ["request", "dependency", "event"],
  },
  {
    id: "capability-relational-database",
    label: "Relational database",
    description: "Stores transactional data with relational constraints.",
    category: "data",
    iconKey: "database",
    connectionRoles: ["data", "dependency"],
  },
  {
    id: "capability-document-database",
    label: "Document database",
    description: "Stores flexible aggregate-oriented documents.",
    category: "data",
    iconKey: "documents",
    connectionRoles: ["data", "dependency"],
  },
  {
    id: "capability-cache",
    label: "Cache",
    description: "Keeps frequently accessed or ephemeral data close to compute.",
    category: "data",
    iconKey: "bolt",
    connectionRoles: ["data", "dependency"],
  },
  {
    id: "capability-queue",
    label: "Message queue",
    description: "Buffers work for asynchronous point-to-point processing.",
    category: "messaging",
    iconKey: "queue",
    connectionRoles: ["event", "dependency"],
  },
  {
    id: "capability-event-stream",
    label: "Event stream",
    description: "Retains ordered events for multiple independent consumers.",
    category: "messaging",
    iconKey: "stream",
    connectionRoles: ["event", "data"],
  },
  {
    id: "capability-object-storage",
    label: "Object storage",
    description: "Stores durable unstructured objects and large blobs.",
    category: "storage",
    iconKey: "archive",
    connectionRoles: ["data", "dependency"],
  },
  {
    id: "capability-identity",
    label: "Identity",
    description: "Authenticates principals and issues authorization claims.",
    category: "security",
    iconKey: "shield-user",
    connectionRoles: ["control", "request"],
  },
  {
    id: "capability-observability",
    label: "Observability",
    description: "Collects and explores telemetry about system behavior.",
    category: "observability",
    iconKey: "pulse",
    connectionRoles: ["data", "event"],
  },
  {
    id: "capability-service-network",
    label: "Service networking",
    description: "Routes, secures, and balances service-to-service traffic.",
    category: "networking",
    iconKey: "network",
    connectionRoles: ["request", "control"],
  },
];

const technologies: ComponentCatalogRecords["technologies"] = [
  {
    id: "technology-react",
    label: "React",
    description: "Component-based library for interactive web interfaces.",
    capabilityIds: ["capability-web-interface"],
    useCases: ["Rich browser applications", "Design-system driven interfaces"],
    strengths: ["Large ecosystem", "Flexible rendering and state choices"],
    tradeoffs: ["Requires architectural choices for routing and data flow"],
    operationalTraits: {
      complexity: "medium",
      scaling: "horizontal",
      state: "stateless",
      skillTags: ["typescript", "react"],
    },
  },
  {
    id: "technology-vue",
    label: "Vue",
    description: "Progressive framework for component-based web interfaces.",
    capabilityIds: ["capability-web-interface"],
    useCases: ["Interactive applications", "Incremental frontend adoption"],
    strengths: ["Approachable conventions", "Integrated reactive primitives"],
    tradeoffs: ["Smaller enterprise ecosystem than React"],
    operationalTraits: {
      complexity: "low",
      scaling: "horizontal",
      state: "stateless",
      skillTags: ["typescript", "vue"],
    },
  },
  {
    id: "technology-nodejs",
    label: "Node.js",
    description: "JavaScript runtime suited to I/O-heavy APIs and services.",
    capabilityIds: ["capability-api", "capability-compute"],
    useCases: ["JSON APIs", "Realtime gateways", "Background I/O processing"],
    strengths: ["Shared TypeScript skills", "Strong network ecosystem"],
    tradeoffs: ["CPU-heavy work needs isolation or worker strategies"],
    operationalTraits: {
      complexity: "low",
      scaling: "horizontal",
      state: "stateless",
      skillTags: ["typescript", "nodejs"],
    },
  },
  {
    id: "technology-go",
    label: "Go",
    description: "Compiled language and runtime for efficient network services.",
    capabilityIds: ["capability-api", "capability-compute"],
    useCases: ["High-throughput APIs", "Concurrent workers", "Platform services"],
    strengths: ["Predictable resource use", "Simple concurrency model"],
    tradeoffs: ["Separate skill set from browser application code"],
    operationalTraits: {
      complexity: "medium",
      scaling: "horizontal",
      state: "stateless",
      skillTags: ["go"],
    },
  },
  {
    id: "technology-containers",
    label: "OCI containers",
    description: "Portable packaged workloads with explicit runtime dependencies.",
    capabilityIds: ["capability-compute"],
    useCases: ["Long-running services", "Custom runtimes", "Portable workloads"],
    strengths: ["Runtime control", "Broad platform compatibility"],
    tradeoffs: ["Requires image lifecycle and orchestration operations"],
    operationalTraits: {
      complexity: "medium",
      scaling: "elastic",
      state: "stateless",
      skillTags: ["containers", "linux"],
    },
  },
  {
    id: "technology-functions",
    label: "Event functions",
    description: "Short-lived handlers activated by requests or events.",
    capabilityIds: ["capability-compute", "capability-api"],
    useCases: ["Bursty event handling", "Small APIs", "Scheduled automation"],
    strengths: ["Fine-grained elastic scaling", "Low idle operations"],
    tradeoffs: ["Runtime limits and cold-start sensitivity"],
    operationalTraits: {
      complexity: "low",
      scaling: "elastic",
      state: "stateless",
      skillTags: ["event-driven", "functions"],
    },
  },
  {
    id: "technology-postgresql",
    label: "PostgreSQL",
    description: "Relational database with rich SQL and extension support.",
    capabilityIds: ["capability-relational-database"],
    useCases: ["Transactional systems", "Complex relational queries", "JSON-assisted models"],
    strengths: ["Strong consistency", "Mature tooling and extensions"],
    tradeoffs: ["Horizontal write scaling needs deliberate architecture"],
    operationalTraits: {
      complexity: "medium",
      scaling: "vertical",
      state: "stateful",
      skillTags: ["sql", "postgresql"],
    },
  },
  {
    id: "technology-mysql",
    label: "MySQL",
    description: "Widely supported relational database for transactional workloads.",
    capabilityIds: ["capability-relational-database"],
    useCases: ["Transactional web systems", "Read-heavy relational workloads"],
    strengths: ["Broad operational support", "Mature replication ecosystem"],
    tradeoffs: ["Advanced SQL behavior varies by engine and version"],
    operationalTraits: {
      complexity: "medium",
      scaling: "vertical",
      state: "stateful",
      skillTags: ["sql", "mysql"],
    },
  },
  {
    id: "technology-mongodb",
    label: "MongoDB",
    description: "Document database for flexible aggregate-oriented records.",
    capabilityIds: ["capability-document-database"],
    useCases: ["Evolving document shapes", "Aggregate-centric access patterns"],
    strengths: ["Flexible documents", "Built-in replication and sharding"],
    tradeoffs: ["Cross-aggregate relational constraints require application design"],
    operationalTraits: {
      complexity: "medium",
      scaling: "horizontal",
      state: "stateful",
      skillTags: ["mongodb", "document-modeling"],
    },
  },
  {
    id: "technology-couchdb",
    label: "Apache CouchDB",
    description: "HTTP-native document database with replication-first design.",
    capabilityIds: ["capability-document-database"],
    useCases: ["Occasionally connected systems", "Multi-site document replication"],
    strengths: ["Conflict-aware replication", "Simple HTTP API"],
    tradeoffs: ["Query patterns are less flexible than general-purpose document stores"],
    operationalTraits: {
      complexity: "medium",
      scaling: "horizontal",
      state: "stateful",
      skillTags: ["couchdb", "document-modeling"],
    },
  },
  {
    id: "technology-redis",
    label: "Redis",
    description: "In-memory data structure server with optional persistence.",
    capabilityIds: ["capability-cache", "capability-queue"],
    useCases: ["Low-latency caching", "Rate limits", "Short-lived work queues"],
    strengths: ["Rich data structures", "Very low latency"],
    tradeoffs: ["Memory economics and durability modes need explicit choices"],
    operationalTraits: {
      complexity: "medium",
      scaling: "horizontal",
      state: "stateful",
      skillTags: ["redis"],
    },
  },
  {
    id: "technology-memcached",
    label: "Memcached",
    description: "Distributed volatile key-value cache with a small surface area.",
    capabilityIds: ["capability-cache"],
    useCases: ["Disposable object caching", "Simple high-throughput cache tiers"],
    strengths: ["Simple operations", "Predictable volatile behavior"],
    tradeoffs: ["No persistence and limited data structures"],
    operationalTraits: {
      complexity: "low",
      scaling: "horizontal",
      state: "stateful",
      skillTags: ["memcached"],
    },
  },
  {
    id: "technology-rabbitmq",
    label: "RabbitMQ",
    description: "Message broker with flexible routing and delivery semantics.",
    capabilityIds: ["capability-queue"],
    useCases: ["Work queues", "Routing-based messaging", "Reliable task delivery"],
    strengths: ["Mature protocols", "Expressive exchange routing"],
    tradeoffs: ["Cluster and backlog behavior require active operations"],
    operationalTraits: {
      complexity: "medium",
      scaling: "horizontal",
      state: "stateful",
      skillTags: ["amqp", "rabbitmq"],
    },
  },
  {
    id: "technology-nats-jetstream",
    label: "NATS JetStream",
    description: "Lightweight messaging with persisted streams and consumers.",
    capabilityIds: ["capability-queue", "capability-event-stream"],
    useCases: ["Low-latency messaging", "Work queues", "Compact event streams"],
    strengths: ["Small operational footprint", "Flexible consumption models"],
    tradeoffs: ["Smaller connector ecosystem than Kafka"],
    operationalTraits: {
      complexity: "medium",
      scaling: "horizontal",
      state: "stateful",
      skillTags: ["nats", "event-driven"],
    },
  },
  {
    id: "technology-kafka",
    label: "Apache Kafka",
    description: "Distributed durable event log for high-throughput streams.",
    capabilityIds: ["capability-event-stream"],
    useCases: ["Event backbones", "Stream processing", "Replayable integration data"],
    strengths: ["High throughput", "Mature connector ecosystem"],
    tradeoffs: ["Operational and partition-model complexity"],
    operationalTraits: {
      complexity: "high",
      scaling: "horizontal",
      state: "stateful",
      skillTags: ["kafka", "event-streaming"],
    },
  },
  {
    id: "technology-pulsar",
    label: "Apache Pulsar",
    description: "Distributed messaging and streaming with separated storage.",
    capabilityIds: ["capability-event-stream", "capability-queue"],
    useCases: ["Multi-tenant streams", "Geo-replicated messaging", "Queue and stream convergence"],
    strengths: ["Flexible subscription models", "Storage/compute separation"],
    tradeoffs: ["Larger operational surface and smaller ecosystem than Kafka"],
    operationalTraits: {
      complexity: "high",
      scaling: "horizontal",
      state: "stateful",
      skillTags: ["pulsar", "event-streaming"],
    },
  },
  {
    id: "technology-s3-api",
    label: "S3-compatible object API",
    description: "Widely implemented HTTP contract for durable object storage.",
    capabilityIds: ["capability-object-storage"],
    useCases: ["Media and artifacts", "Data exchange", "Backups"],
    strengths: ["Portable client ecosystem", "Scales to large object sets"],
    tradeoffs: ["Not a filesystem and offers limited transactional semantics"],
    operationalTraits: {
      complexity: "low",
      scaling: "elastic",
      state: "stateful",
      skillTags: ["object-storage", "s3-api"],
    },
  },
  {
    id: "technology-minio",
    label: "MinIO",
    description: "Self-hostable object storage implementing the S3 API.",
    capabilityIds: ["capability-object-storage"],
    useCases: ["On-premises object storage", "Development parity", "Data platforms"],
    strengths: ["S3 client compatibility", "Deployment control"],
    tradeoffs: ["Durability and capacity operations remain the team's responsibility"],
    operationalTraits: {
      complexity: "high",
      scaling: "horizontal",
      state: "stateful",
      skillTags: ["minio", "object-storage"],
    },
  },
  {
    id: "technology-keycloak",
    label: "Keycloak",
    description: "Open-source identity and access management server.",
    capabilityIds: ["capability-identity"],
    useCases: ["OIDC and SAML federation", "Workforce or customer identity"],
    strengths: ["Broad protocol support", "Deployment control"],
    tradeoffs: ["Security patching, scaling, and availability are self-managed"],
    operationalTraits: {
      complexity: "high",
      scaling: "horizontal",
      state: "stateful",
      skillTags: ["oidc", "keycloak", "identity"],
    },
  },
  {
    id: "technology-ory",
    label: "Ory",
    description: "Composable identity services built around modern authorization protocols.",
    capabilityIds: ["capability-identity"],
    useCases: ["Headless customer identity", "Fine-grained authorization"],
    strengths: ["API-first components", "Separation of identity concerns"],
    tradeoffs: ["Composition requires more application integration decisions"],
    operationalTraits: {
      complexity: "high",
      scaling: "horizontal",
      state: "stateful",
      skillTags: ["oidc", "ory", "identity"],
    },
  },
  {
    id: "technology-opentelemetry",
    label: "OpenTelemetry",
    description: "Vendor-neutral telemetry APIs, SDKs, and collection protocol.",
    capabilityIds: ["capability-observability"],
    useCases: ["Traces, metrics, and logs", "Vendor-neutral instrumentation"],
    strengths: ["Broad ecosystem support", "Backend portability"],
    tradeoffs: ["Still requires a telemetry storage and analysis backend"],
    operationalTraits: {
      complexity: "medium",
      scaling: "horizontal",
      state: "stateless",
      skillTags: ["opentelemetry", "observability"],
    },
  },
  {
    id: "technology-prometheus",
    label: "Prometheus",
    description: "Time-series monitoring system built around metric scraping and queries.",
    capabilityIds: ["capability-observability"],
    useCases: ["Infrastructure metrics", "Service-level indicators", "Alerting"],
    strengths: ["Powerful metric query model", "Cloud-native ecosystem"],
    tradeoffs: ["Long-term retention and very large cardinality need extensions"],
    operationalTraits: {
      complexity: "medium",
      scaling: "vertical",
      state: "stateful",
      skillTags: ["prometheus", "observability"],
    },
  },
  {
    id: "technology-envoy",
    label: "Envoy Proxy",
    description: "Programmable service and edge proxy with rich telemetry.",
    capabilityIds: ["capability-service-network"],
    useCases: ["Service mesh data planes", "Edge proxying", "Advanced traffic policy"],
    strengths: ["Dynamic control APIs", "Deep protocol observability"],
    tradeoffs: ["Configuration and control-plane complexity"],
    operationalTraits: {
      complexity: "high",
      scaling: "horizontal",
      state: "stateless",
      skillTags: ["envoy", "networking"],
    },
  },
  {
    id: "technology-nginx",
    label: "NGINX",
    description: "Web server and reverse proxy for HTTP traffic management.",
    capabilityIds: ["capability-service-network"],
    useCases: ["Reverse proxying", "Static delivery", "Load balancing"],
    strengths: ["Mature and efficient", "Broad operational familiarity"],
    tradeoffs: ["Dynamic service-mesh patterns require additional management"],
    operationalTraits: {
      complexity: "low",
      scaling: "horizontal",
      state: "stateless",
      skillTags: ["nginx", "networking"],
    },
  },
];

export const componentCatalogRecords: ComponentCatalogRecords = {
  capabilities,
  technologies,
};
