import type { ProviderCatalogRecords } from "@/application/contracts";

const providers: ProviderCatalogRecords["providers"] = [
  {
    id: "provider-aws",
    label: "Amazon Web Services",
    description: "AWS public-cloud services and managed platforms.",
    iconKey: "aws",
  },
  {
    id: "provider-azure",
    label: "Microsoft Azure",
    description: "Azure public-cloud services and managed platforms.",
    iconKey: "azure",
  },
];

const services: ProviderCatalogRecords["services"] = [
  {
    id: "service-aws-fargate",
    providerId: "provider-aws",
    label: "AWS Fargate",
    description: "Runs container workloads without managing compute instances.",
    capabilityIds: ["capability-compute", "capability-api"],
    compatibleTechnologyIds: [
      "technology-containers",
      "technology-go",
      "technology-nodejs",
      "technology-java",
      "technology-python",
      "technology-rust",
    ],
    managementModel: "managed-platform",
    managedServiceContext: "AWS manages the container compute plane; teams manage images and task definitions.",
    tradeoffs: [
      "Less host-level control than instance-based container hosting",
      "Long-running tasks incur provisioned resource charges",
    ],
  },
  {
    id: "service-aws-lambda",
    providerId: "provider-aws",
    label: "AWS Lambda",
    description: "Executes event-driven functions with request-based scaling.",
    capabilityIds: ["capability-compute", "capability-api"],
    compatibleTechnologyIds: [
      "technology-functions",
      "technology-go",
      "technology-nodejs",
      "technology-java",
      "technology-python",
      "technology-rust",
    ],
    managementModel: "serverless",
    managedServiceContext: "AWS manages runtime capacity and scaling; teams deploy function code and configuration.",
    tradeoffs: [
      "Execution limits constrain long-running workloads",
      "Cold starts can affect latency-sensitive paths",
    ],
  },
  {
    id: "service-aws-rds-postgresql",
    providerId: "provider-aws",
    label: "Amazon RDS for PostgreSQL",
    description: "Operates PostgreSQL databases with managed maintenance and recovery features.",
    capabilityIds: ["capability-database", "capability-relational-database"],
    compatibleTechnologyIds: ["technology-postgresql"],
    managementModel: "fully-managed",
    managedServiceContext: "AWS manages database infrastructure, backups, patch workflows, and failover options.",
    tradeoffs: [
      "Extension and host access are more constrained than self-managed PostgreSQL",
      "Scaling and high-availability choices remain explicit configuration decisions",
    ],
  },
  {
    id: "service-aws-rds-mysql",
    providerId: "provider-aws",
    label: "Amazon RDS for MySQL",
    description: "Operates MySQL databases with managed maintenance and recovery features.",
    capabilityIds: ["capability-database", "capability-relational-database"],
    compatibleTechnologyIds: ["technology-mysql"],
    managementModel: "fully-managed",
    managedServiceContext: "AWS manages database infrastructure, backups, patch workflows, and failover options.",
    tradeoffs: [
      "Host access and some engine configuration are constrained",
      "Read and write scaling require deliberate topology choices",
    ],
  },
  {
    id: "service-aws-documentdb",
    providerId: "provider-aws",
    label: "Amazon DocumentDB",
    description: "Provides a managed document database with MongoDB-compatible APIs.",
    capabilityIds: ["capability-database", "capability-document-database"],
    compatibleTechnologyIds: ["technology-mongodb"],
    managementModel: "managed-cluster",
    managedServiceContext: "AWS manages cluster infrastructure and backups while applications use supported MongoDB APIs.",
    tradeoffs: [
      "MongoDB API compatibility is not identical to running MongoDB",
      "Portability depends on the features and operators an application uses",
    ],
  },
  {
    id: "service-aws-elasticache",
    providerId: "provider-aws",
    label: "Amazon ElastiCache",
    description: "Provides managed in-memory caches for low-latency data access.",
    capabilityIds: ["capability-cache"],
    compatibleTechnologyIds: ["technology-memcached", "technology-redis"],
    managementModel: "managed-cluster",
    managedServiceContext: "AWS manages cache nodes, replacement, monitoring, and configured replication.",
    tradeoffs: [
      "Capacity and topology still require workload-aware configuration",
      "Engine features and versions follow the managed service lifecycle",
    ],
  },
  {
    id: "service-aws-amazon-mq",
    providerId: "provider-aws",
    label: "Amazon MQ for RabbitMQ",
    description: "Runs managed RabbitMQ brokers for queue-based messaging.",
    capabilityIds: ["capability-queue"],
    compatibleTechnologyIds: ["technology-rabbitmq"],
    managementModel: "managed-cluster",
    managedServiceContext: "AWS manages broker provisioning and maintenance; teams retain RabbitMQ protocol semantics.",
    tradeoffs: [
      "Broker sizing and topology affect throughput and availability",
      "Managed engine versions can lag self-managed releases",
    ],
  },
  {
    id: "service-aws-msk",
    providerId: "provider-aws",
    label: "Amazon Managed Streaming for Apache Kafka",
    description: "Runs managed Apache Kafka clusters for durable event streams.",
    capabilityIds: ["capability-event-stream"],
    compatibleTechnologyIds: ["technology-kafka"],
    managementModel: "managed-cluster",
    managedServiceContext: "AWS manages Kafka brokers and infrastructure while teams design topics, partitions, and consumers.",
    tradeoffs: [
      "Kafka partitioning and consumer operations remain application concerns",
      "Cluster choices influence cost and scaling behavior",
    ],
  },
  {
    id: "service-aws-s3",
    providerId: "provider-aws",
    label: "Amazon S3",
    description: "Stores durable objects behind the S3 API.",
    capabilityIds: ["capability-object-storage"],
    compatibleTechnologyIds: ["technology-s3-api"],
    managementModel: "serverless",
    managedServiceContext: "AWS manages storage capacity and durability; teams manage buckets, access, and lifecycle policy.",
    tradeoffs: [
      "Object semantics differ from a shared filesystem",
      "Request, transfer, and retention patterns affect cost",
    ],
  },
  {
    id: "service-aws-cognito",
    providerId: "provider-aws",
    label: "Amazon Cognito",
    description: "Provides managed user directories, federation, and application tokens.",
    capabilityIds: ["capability-identity"],
    compatibleTechnologyIds: [],
    managementModel: "serverless",
    managedServiceContext: "AWS operates the identity service; teams configure user pools, federation, and application integration.",
    tradeoffs: [
      "Authentication flows and customization follow service-specific constraints",
      "Migration away requires an explicit identity-data strategy",
    ],
  },
  {
    id: "service-aws-vpc-lattice",
    providerId: "provider-aws",
    label: "Amazon VPC Lattice",
    description: "Connects and controls service-to-service traffic across VPCs.",
    capabilityIds: ["capability-service-network"],
    compatibleTechnologyIds: [],
    managementModel: "fully-managed",
    managedServiceContext: "AWS manages the service-network data plane; teams define services, policies, and routing.",
    tradeoffs: [
      "Adoption couples service networking policy to AWS constructs",
      "Cross-provider traffic needs separate integration",
    ],
  },
  {
    id: "service-aws-cloudwatch",
    providerId: "provider-aws",
    label: "Amazon CloudWatch",
    description: "Collects, stores, and explores metrics, logs, alarms, and traces.",
    capabilityIds: ["capability-observability"],
    compatibleTechnologyIds: ["technology-opentelemetry", "technology-prometheus"],
    managementModel: "fully-managed",
    managedServiceContext: "AWS operates telemetry storage and analysis services; teams configure collection, retention, and alerts.",
    tradeoffs: [
      "Telemetry volume and retention directly affect cost",
      "Query and dashboard workflows are specific to the AWS observability stack",
    ],
  },
  {
    id: "service-azure-container-apps",
    providerId: "provider-azure",
    label: "Azure Container Apps",
    description: "Runs containerized applications on a managed, elastic platform.",
    capabilityIds: ["capability-compute", "capability-api"],
    compatibleTechnologyIds: [
      "technology-containers",
      "technology-go",
      "technology-nodejs",
      "technology-java",
      "technology-python",
      "technology-rust",
    ],
    managementModel: "managed-platform",
    managedServiceContext: "Azure manages orchestration and scaling; teams manage images, revisions, and application configuration.",
    tradeoffs: [
      "Platform abstractions limit low-level orchestration control",
      "Networking and scaling behavior require service-specific configuration",
    ],
  },
  {
    id: "service-azure-functions",
    providerId: "provider-azure",
    label: "Azure Functions",
    description: "Executes event-driven functions with elastic hosting options.",
    capabilityIds: ["capability-compute", "capability-api"],
    compatibleTechnologyIds: [
      "technology-functions",
      "technology-nodejs",
      "technology-java",
      "technology-python",
      "technology-rust",
    ],
    managementModel: "serverless",
    managedServiceContext: "Azure manages function hosting and event integration; teams deploy code and select a hosting plan.",
    tradeoffs: [
      "Latency and scaling characteristics vary by hosting plan",
      "Runtime and execution constraints shape workload suitability",
    ],
  },
  {
    id: "service-azure-postgresql",
    providerId: "provider-azure",
    label: "Azure Database for PostgreSQL",
    description: "Operates PostgreSQL databases with managed maintenance and availability options.",
    capabilityIds: ["capability-database", "capability-relational-database"],
    compatibleTechnologyIds: ["technology-postgresql"],
    managementModel: "fully-managed",
    managedServiceContext: "Azure manages database infrastructure, backups, patching, and configured availability.",
    tradeoffs: [
      "Extension and host access are more constrained than self-managed PostgreSQL",
      "Compute and storage scaling remain explicit design choices",
    ],
  },
  {
    id: "service-azure-mysql",
    providerId: "provider-azure",
    label: "Azure Database for MySQL",
    description: "Operates MySQL databases with managed maintenance and availability options.",
    capabilityIds: ["capability-database", "capability-relational-database"],
    compatibleTechnologyIds: ["technology-mysql"],
    managementModel: "fully-managed",
    managedServiceContext: "Azure manages database infrastructure, backups, patching, and configured availability.",
    tradeoffs: [
      "Host access and some engine configuration are constrained",
      "Scaling and replica topology require deliberate configuration",
    ],
  },
  {
    id: "service-azure-cosmos-mongodb-vcore",
    providerId: "provider-azure",
    label: "Azure Cosmos DB for MongoDB vCore",
    description: "Provides managed document storage through MongoDB-compatible tooling and APIs.",
    capabilityIds: ["capability-database", "capability-document-database"],
    compatibleTechnologyIds: ["technology-mongodb"],
    managementModel: "managed-cluster",
    managedServiceContext: "Azure manages the database cluster while applications use supported MongoDB drivers and tools.",
    tradeoffs: [
      "Compatibility and operational behavior differ from self-managed MongoDB",
      "Portability depends on the features and extensions an application uses",
    ],
  },
  {
    id: "service-azure-managed-redis",
    providerId: "provider-azure",
    label: "Azure Managed Redis",
    description: "Provides managed Redis-compatible in-memory data services.",
    capabilityIds: ["capability-cache"],
    compatibleTechnologyIds: ["technology-redis"],
    managementModel: "managed-cluster",
    managedServiceContext: "Azure manages Redis Enterprise infrastructure, scaling options, and availability features.",
    tradeoffs: [
      "Cluster policy and tier choices affect command behavior and cost",
      "The managed engine lifecycle differs from community Redis deployments",
    ],
  },
  {
    id: "service-azure-service-bus",
    providerId: "provider-azure",
    label: "Azure Service Bus",
    description: "Provides managed queues and topics for reliable enterprise messaging.",
    capabilityIds: ["capability-queue"],
    compatibleTechnologyIds: [],
    managementModel: "fully-managed",
    managedServiceContext: "Azure operates the broker service; teams design namespaces, queues, topics, and delivery handling.",
    tradeoffs: [
      "Messaging semantics and quotas are Azure-specific",
      "Throughput and isolation characteristics vary by tier",
    ],
  },
  {
    id: "service-azure-event-hubs",
    providerId: "provider-azure",
    label: "Azure Event Hubs",
    description: "Ingests and retains high-volume event streams with partitioned consumers.",
    capabilityIds: ["capability-event-stream"],
    compatibleTechnologyIds: ["technology-kafka"],
    managementModel: "fully-managed",
    managedServiceContext: "Azure manages the event-ingestion platform; teams configure partitions, retention, and consumers.",
    tradeoffs: [
      "Kafka protocol support does not make every Kafka feature available",
      "Partition and throughput choices remain application design concerns",
    ],
  },
  {
    id: "service-azure-blob-storage",
    providerId: "provider-azure",
    label: "Azure Blob Storage",
    description: "Stores durable unstructured objects in Azure storage accounts.",
    capabilityIds: ["capability-object-storage"],
    compatibleTechnologyIds: [],
    managementModel: "serverless",
    managedServiceContext: "Azure manages storage capacity and durability; teams manage containers, access, and lifecycle policy.",
    tradeoffs: [
      "Azure Blob APIs differ from the S3 API ecosystem",
      "Redundancy, access tier, and transfer patterns affect cost",
    ],
  },
  {
    id: "service-azure-entra-id",
    providerId: "provider-azure",
    label: "Microsoft Entra ID",
    description: "Provides managed identity, authentication, federation, and access control.",
    capabilityIds: ["capability-identity"],
    compatibleTechnologyIds: [],
    managementModel: "fully-managed",
    managedServiceContext: "Microsoft operates the identity platform; teams configure tenants, applications, policies, and federation.",
    tradeoffs: [
      "Tenant and policy design require specialist identity knowledge",
      "Application integration becomes coupled to Entra configuration and lifecycle",
    ],
  },
  {
    id: "service-azure-application-gateway",
    providerId: "provider-azure",
    label: "Azure Application Gateway",
    description: "Routes and protects HTTP application traffic at layer seven.",
    capabilityIds: ["capability-service-network"],
    compatibleTechnologyIds: [],
    managementModel: "fully-managed",
    managedServiceContext: "Azure manages gateway infrastructure; teams configure listeners, routes, health probes, and policies.",
    tradeoffs: [
      "Gateway configuration and behavior are Azure-specific",
      "Capacity, zone, and firewall options require explicit planning",
    ],
  },
  {
    id: "service-azure-monitor",
    providerId: "provider-azure",
    label: "Azure Monitor",
    description: "Collects and analyzes application and infrastructure telemetry.",
    capabilityIds: ["capability-observability"],
    compatibleTechnologyIds: ["technology-opentelemetry", "technology-prometheus"],
    managementModel: "fully-managed",
    managedServiceContext: "Azure operates telemetry ingestion and analysis services; teams configure collection, retention, and alerts.",
    tradeoffs: [
      "Telemetry volume and retention directly affect cost",
      "Query and dashboard workflows are specific to the Azure observability stack",
    ],
  },
];

export const providerCatalogRecords: ProviderCatalogRecords = {
  providers,
  services,
};
